general:
  site_url: 'https://droitwichchiro.com'
  address:
    street_address: '2 Middle Lane'
    reference: 'Gaudet Luce Leisure Complex'
    town_or_city: Droitwich
    state_or_province: England
    post_code: WR9 7JR
    country: United Kingdom
    geo_coordinates:
      latitude: 52.335775161621484 
      longitude: -2.117222307979403
  address_url: 'https://goo.gl/maps/5P3HRqoJBcniB49UA'
  google_maps_embed_url: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2442.308651707626!2d-2.131519222739017!3d52.25593997199317!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4870ee77ee2db79b%3A0xda1e6fdf20451880!2sDroitwich%20Back%20%26%20Neck%20Clinic%20-%20Chiropractor!5e0!3m2!1sen!2sbr!4v1689690330301!5m2!1sen!2sbr'
  email: 'info@droitwichchiro.com'
  phone: '+44 1 905 798 226'
  social:
    - channel: "Facebook"
      add_to_chat_bubble: false
      url: 'https://facebook.com'
    - channel: "WhatsApp"
      add_to_chat_bubble: true
      url: 'https://wa.me/'
    - channel: "Messenger"
      add_to_chat_bubble: true
      url: 'https://m.me'
opening_hours:
  - day: Monday
    opens: 9:45am
    closes: 6:30pm
  - day: Tuesday
    opens: 9:45am
    closes: 6:30pm
  - day: Wednesday
    opens: 9:45am
    closes: 6:30pm
  - day: Thursday
    opens: 9:45am
    closes: 6:30pm
  - day: Friday
    opens: Closed
    closes: Closed
  - day: Saturday
    opens: Closed  
    closes: Closed  
  - day: Sunday
    opens: Closed  
    closes: Closed
branding:
  site_title: Droitwich Back and Neck Clinic
  nav_logo_image: /assets/images/droitwich-logo-final.png
  footer_logo_image: /assets/images/droitwich-logo-white.png
  preview_image: /assets/images/logo.png
navigation:
  menus:           
    - name: About
      url: '/about-us'
      is_dropdown: false
      style_as_button: false
      submenus:              
        - name:
          url:
    - name: Chiropractic
      url: '#'
      is_dropdown: true
      style_as_button: false
      submenus:              
        - name: Your First Visit
          url: /new-patients
        - name: Holistic Health Process
          url: /holistic-health-process
    - name: Conditions
      url: '/conditions'
      is_dropdown: true
      style_as_button: false
      submenus:
        - name: Back Pain 
          url: /conditions/back-pain
        - name: Neck Pain 
          url: /conditions/neck-pain
        - name: Shoulder Pain
          url: /conditions/shoulder-pain
        - name: Knee Pain
          url: /conditions/knee-pain
        - name: Elbow Pain
          url: /conditions/elbow-pain
        - name: Migraines
          url: /conditions/migraines
        - name: Disc Injuries
          url: /conditions/disc-injuries
        - name: Dizziness 
          url: /conditions/dizziness
        - name: Headaches 
          url: /conditions/headaches      
    - name: FAQS
      url: '/faqs'
      is_dropdown: false
      style_as_button: false
      submenus:
        - name:
          url:    
    - name: Blog
      url: '/blog'
      is_dropdown: false
      style_as_button: false
      submenus:
        - name:
          url:    
    - name: Contact
      url: '/contact'
      is_dropdown: false
      style_as_button: false
      submenus:             
        - name:
          url:
    - name: Book now
      url: '/book-online'
      is_dropdown: false
      style_as_button: true
      submenus:                 
        - name:
          url:
seo:
  site_description_text: Local chiropractor serving the Droitwich, Worcester and Bromsgrove communities.
  keywords: [chiropractor droitwich]
configuration:
  google_tag_manager_id:
  head_code_block: >-
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Alata&family=Questrial&display=swap" rel="stylesheet preload" as="style" crossorigin="anonymous" type="text/css">
  body_code_block: >-

  custom_css_code_block: >-
  